### PR TITLE
Enhance App and Fix Bugs

### LINKED ISSUE #11: Component distribution
Try dividing the whole app into smaller components. For example: create a separate component for both header and footer.

### LINKED ISSUE #21: axios promise isn't allowed to complete before redirection to root
``` js
axios.post('http://localhost:5000/exercises/add', exercise)
  .then(res => console.log(res.data));

window.location = '/';
```

Modifying `window.location` outside the promise returned by `axios` causes the application to reload before the request is successfully complete. Hence, the API call fails. 
I would like to be assigned this issue.

### LINKED ISSUE #30: Update .gitignore
# Update .gitignore
The `.gitignore` file needs to be updated to ignore files from within the `backend` directory too. Currently, the commits are polluted with the `backend/node_modules` directory.

### PR DESCRIPTION
**Pull request by paramsiddharth**
# Enhance App and Fix Bugs

## Issues Resolved
- Resolves #11: **Component Distribution**
- Resolves #21: **axios promise isn't allowed to complete before redirection to root**
- Resolves #30: **Update .gitignore**

## Modifications
- Removed `backend` pollutants by clearing up the cache and recommitting changes.
  `backend/node_modules` is unnecessarily occupying nodes in the repository. When needed, one can do a fresh `npm install` or `npm ci` in the `backend` directory to get the back-end ready.
- Updated `.gitignore` to exclude the `backend/node_modules` from further commits. The updated `package.json` and other required files will always be included.
  ``` bash
  backend
  │
  ├── models
  │   ├── exercise.model.js
  │   └── user.model.js
  ├── package-lock.json
  ├── package.json
  ├── routes
  │   ├── exercises.js
  │   └── users.js
  └── server.js
  ```
- Fixed redirection issue with `axios` calls by enclosing the `window.location` assignments in `.then()` blocks.
  ``` js
  ...
  .then(() => window.location = '/');
  ...
  ```
- Create a `<Footer />` component using the same Bootstrap style as used by the rest of the application.
- Create a `<CustomForm {#props} />` component for usage in the `<CreateExercise />` and `<EditExercise />` components.
  Why? Because both the components have the same form structure. The only difference is the text inside the submission button. Hence, we judiciously separate the application into components without code-repetition.
  The component accepts the desired methods and values as `props`.
  ``` js
  <CustomForm
    onSubmit={this.onSubmit}
    onChangeUsername={this.onChangeUsername}
    onChangeDescription={this.onChangeDescription}
    onChangeDate={this.onChangeDate}
    onChangeDueDate={this.onChangeDueDate}
    onChangeDuration={this.onChangeUsername}
    state={{
      users: this.state.users,
      username: this.state.username,
      date: this.state.date,
      ddate: this.state.ddate,
      duration: this.state.duration,
      description: this.state.description
    }}
    submitMessage={'<Submission Button Message>'}
    />
  ```

### CODE REVIEW

**Comment by garimasingh128** [comment]
Hey the code looks good but you have added the node modules of backend folder also. Please put them in gitignore and then push again! Check here https://github.com/garimasingh128/ToDoista/pull/33/files

**Comment by paramsiddharth** [comment]
@garimasingh128 I removed it in the most recent commit! :) Please verify: https://github.com/paramsiddharth/ToDoista/tree/master/backend

**Comment by garimasingh128** [comment]
Yup, your forked repo looks clean but still the node modules of backend are visible in this PR. Can you please look into it or create a fresh PR after closing this one?

**Comment by paramsiddharth** [comment]
Got it!

**Comment by paramsiddharth** [comment]
I created a fresh PR at #51. Please review.

**Pull request closed without merging**
