### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by Rishikeshrajrxl**
Here I have added  Contributors image in a formated manner. It looks wonderful now.

related to issue #57

### CODE REVIEW

**Comment by Rishikeshrajrxl** [comment]
@garimasingh128, kindly review my PR

**Comment by garimasingh128** [comment]
Can you use a github action for this? Also you removed one of the contributors [Mrinal](https://github.com/mrinal41298) from this.

**Comment by Rishikeshrajrxl** [comment]
> Can you use a github action for this? Also you removed one of the contributors [Mrinal](https://github.com/mrinal41298) from this.

@garimasingh128,  there is no account to for Mrinal41298. Please check

**Comment by garimasingh128** [comment]
My fault sorry! It's @mrinal4 
And all-contributors bot will work fine!

**Comment by Rishikeshrajrxl** [comment]
@garimasingh128, what next then, should I do futher changes or simply close this PR

**Comment by garimasingh128** [comment]
You can try any github bot. For reference: https://github.com/saadpasta/developerFolio
We can't be using static readme contributors as of now.

**Comment by Rishikeshrajrxl** [comment]
@all-contributors please add @Rishikeshrajrxl  for infrastructure, tests and code

**Comment by Rishikeshrajrxl** [comment]
@all-contributors please add @Rishikeshrajrxl  for code

**Comment by garimasingh128** [comment]
Let me know if it works or i can set it up myself.

**Comment by m-code12** [comment]
@garimasingh128 Can you please install [this bot](https://github.com/apps/allcontributors) on this repo, since only you have the permissions to do so. After that, I'll do the needful.

**Comment by garimasingh128** [comment]
ok i have installed

**Comment by m-code12** [comment]
@all-contributors please add @garimasingh128 for infrastructure, tests and code

**Comment by m-code12** [comment]
@all-contributors please add @gitter-badger for code

**Comment by m-code12** [comment]
@all-contributors please add @Rishikeshrajrxl for code

**Comment by garimasingh128** [comment]
Working fine I guess!

**Comment by m-code12** [comment]
> Working fine I guess!

Yes!

**Comment by m-code12** [comment]
I'll add all the contributors, please merge these pull requests.

**Comment by m-code12** [comment]
@all-contributors please add @Vishal-raj-1 for code

**Comment by m-code12** [comment]
@all-contributors please add @m-code12 for code

**Comment by m-code12** [comment]
@garimasingh128 Should I  remove this section then?
Screenshot (306)

**Comment by garimasingh128** [comment]
No, I will comment it out for now!

**Comment by garimasingh128** [comment]
If I am adding someone its showing This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token : in JSON at position 364
Can u check?

**Comment by m-code12** [comment]
@garimasingh128 
Please update my points on the leaderboard for resolving this issue. Thanks :)

**Comment by garimasingh128** [comment]
Yup sure, I will update the points. I tried for other contributors and its working fine.

**Pull request closed without merging**
