### PR TITLE
Organized directory structure and beautified README

### LINKED ISSUE #60: Beautify the README with badges and heading  Centered
I would like to beautify the readme file with badges and making the header center and improving a little which gives it a stunning look since the readme file is the thing people see first and notice

Demo

image

@garimasingh128, kindly assign me this issues.

### PR DESCRIPTION
**Pull request by nerdynikhil**
Closes #60 

- Organized folder structure i.e. added "/screenshots" to maintain professionalism.
- Made semantic corrections.

### CODE REVIEW

**Comment by nerdynikhil** [comment]
@garimasingh128 Can you help me make corrections to get the checks successful?

**Comment by garimasingh128** [comment]
Most of these are related to Netlify hosting so let it be as sometimes the build fails. The important ones of Codacy are green so it's great. Also, please change base branch to develop.

**Comment by nerdynikhil** [comment]
> Most of these are related to Netlify hosting so let it be as sometimes the build fails. The important ones of Codacy are green so it's great. Also, please change base branch to develop.

I've changed the branch to _develop_. Thanks

**Comment by garimasingh128** [comment]
Conflicts in readme. please resolve.

**Comment by nerdynikhil** [comment]
@garimasingh128 Can you help? All the changes that I've made are conflicts itself! LOL

**Comment by garimasingh128** [comment]
Can you check again? I resolved some conflicts.

**Review by garimasingh128 — APPROVED** [review]

**Pull request merged**
