### PR TITLE
Adding templates for PRs and ISSUES

### LINKED ISSUE #7: Adding templates for PRs and Issues
- PR Template reference: https://gist.github.com/garimasingh128/f81418db6f4dbe6946e6d1abaf3ec8ec
- Issue template

### PR DESCRIPTION
**Pull request by Halix267**
closes #7 
Adding templates for PRs and ISSUES

### CODE REVIEW

**Comment by Halix267** [comment]
@garimasingh128  I have made the changes u told to me . Plzz review it now

**Comment by garimasingh128** [comment]
You don't have to create a separate folder for templates. Follow this https://github.com/garimasingh128/profext

**Comment by Halix267** [comment]
@garimasingh128  I deleted the templates folder , Now this pr is good??

**Comment by garimasingh128** [comment]
PR Template is okay but put all issue templates in a single folder by name "ISSUE_TEMPLATES"

**Comment by Halix267** [comment]
ok

**Comment by Halix267** [comment]
@garimasingh128 done.

**Comment by garimasingh128** [comment]
User story template is also an issue template. Please put it under the same folder.

**Comment by Halix267** [comment]
Ok wait

**Comment by Halix267** [comment]
@garimasingh128 done

**Pull request merged**
