### PR TITLE
Added CODE_OF_CONDUCT.md, CONTRIBUTING.md and Logos, Name ideas, Font Families, Wallpapers, Color Palettes to the design folder.

### PR DESCRIPTION
**Pull request by Pranav016**
1. Added CODE_OF_CONDUCT.md, CONTRIBUTING.md and Logos, Name ideas, Font Families, Wallpapers, Color Palettes to the design folder in the `develop` branch.

2. This contribution was made under NJACK winter of code so please merge it after 1 Dec, 2020 so that it gets counted towards it.

3. Solves issue #12 and #6 

4. For Design folder- A lot of time and effort was put into collecting these resources. Let me know if you like these.
Checkout the design.md file in the design folder for the complete brief.

### CODE REVIEW

**Comment by Pranav016** [comment]
All the necessary files have been added to the develop branch 👍

**Comment by Pranav016** [comment]
@garimasingh128 Can you take a look at the files added. Thanks

**Comment by Pranav016** [comment]
@garimasingh128  I have made all the suggested changes for these issues. Do let me know if there are any other changes to be made so that I can get this pull request merged. I'd be happy to improve it as much as I can :)

**Comment by Pranav016** [comment]
@garimasingh128 Please review this PR, a lot of effort was put into this. Thanks!

**Comment by Pranav016** [comment]
> @garimasingh128 Please review this PR, a lot of effort was put into this. Thanks!

Please merge this PR if it seems good. Thanks 👍

**Comment by Pranav016** [comment]
@garimasingh128 Please merge this, alot of effort was put into this! 👍

**Comment by garimasingh128** [comment]
I am not merging it as of now as I am waiting for other people who claimed the issue to make a PR and we can choose the best ideas. but I have awarded you suitable points for your efforts and it will be reflected on the leaderboard.

**Pull request closed without merging**
